### ISSUE TITLE
Gives warning filename should be matched with class name on migration files

### ISSUE THREAD

**Issue by jaynarayan89** [louisl/CodeIgniter4-Standard#11]
for the migration files  class name is not same as filename because filename is prefixed with time stamp or number.

**Comment by louisl** [comment]
Apologies for the late reply, thanks for the report, I'll look into it asap.

**Comment by louisl** [comment]
@jaynarayan89 

I've been very busy with other work so haven't had a chance to take a look at this yet, could you please post a small example of a migrations file with the filename. I need to look for a consistency that will allow me to exclude that rule for migration files.

**Comment by jaynarayan89** [comment]
@louisl  Please check this [Gist](https://gist.github.com/jaynarayan89/e23ad3923ff8f96dddd35f8e8784bcce)

**Comment by louisl** [comment]
This has been fixed in release [v1.0.0-beta0012](https://github.com/louisl/CodeIgniter4-Standard/releases/tag/v1.0.0-beta0012).
