### ISSUE TITLE
Transfer repo to bcit-ci

### ISSUE THREAD

**Issue by jim-parry** [louisl/CodeIgniter4-Standard#16]
I am now a collaborator :)
If you grant me admin rights to the repo, I can do the transfer.

For composer:
- we will need to update composer.json to reflect the new repo location
- we may need to change the listing on packagist.org or add a new entry "codeigniter4/standard"

**Comment by louisl** [comment]
> If you grant me admin rights to the repo, I can do the transfer.

Do you know where I set this I cant find it?

**Comment by jim-parry** [comment]
In settings > collaborators
You should see my name, with a combobox beside it with the rights I have for the repo.

**Comment by louisl** [comment]
I think that may be only be a Paid account option only, There's no dropdown next to your name. I do see one on collaborators for my company projects though.

I think I might have to use the transfer option in settings > danger zone

https://help.github.com/articles/about-repository-transfers/

<img width="778" alt="screenshot 2017-12-11 17 16 01" src="https://user-images.githubusercontent.com/1140394/33844087-20dff7b2-de97-11e7-9128-4c4c8f696e69.png">

**Comment by louisl** [comment]
So I think I should transfer to "bcit-ci"

**Comment by jim-parry** [comment]
agreed

**Comment by louisl** [comment]
Did you get an email?

After confirming I got this notification.

<img width="507" alt="screenshot 2017-12-11 18 58 37" src="https://user-images.githubusercontent.com/1140394/33848412-8ffee852-dea5-11e7-8f23-1da63a3e8821.png">

**Comment by jim-parry** [comment]
I didn't get notified. It looks like it is a bit more complicated than anticipated.

I have invited you to be a member of "bcit-ci".

Might have to tweak your settings within the org, but that will have to wait until later today ... it is final exam week, and I am off to inflict punishment :-/


Thanks,

Jim

________________________________

**Comment by louisl** [comment]
OK, I accepted the invite, tried again and .got the same error. I'll contact Github support.

**Comment by jim-parry** [comment]
I just gave you admin access, but that is for the entire organization. I will fix that to maintainer rights on your repo once transferred.

________________________________

**Comment by louisl** [comment]
Thanks, it's transferred :-)

**Comment by jim-parry** [comment]
Yay! I have made you an admin on the repo (as well as Lonnie), and just a "member" of bcit-ci.
I will announce this on the forum, but later this afternoon!
Thank you!!

**Comment by louisl** [comment]
Thanks @jim-parry, Hold off on the announcement for a little while I'm going to get the readme links, composer.json, travis job and packagist updated.

**Comment by louisl** [comment]
@jim-parry,

OK, just need to sort out packagist now, I think I add you as a maintainer then you can set up a package with the right namespace. Should I add "bcit-ci" for packagist? because I know there's a few different codeIgniter ones?

**Comment by jim-parry** [comment]
Our relevant "vendor" name is "codeigniter4".

________________________________

**Comment by louisl** [comment]
Ok it's all ready to go with release 1.0.1.

It seems you will need to add it in packagist to the codeigniter4 account then I abandon mine with a reference to the new one.

https://github.com/composer/packagist/issues/47

**Comment by jim-parry** [comment]
aaaaaaand, we are up & running. See

https://forum.codeigniter.com/thread-69545.html

________________________________

**Comment by louisl** [comment]
Nice one!, I've abandoned my version so anyone trying to install from louisl gets the message.

Let the mayhem begin!

**Comment by louisl** [comment]
Oh by the way, do you want me to look at getting Travis CI build for CodeIgniter4 checking against the standard?

**Comment by louisl** [comment]
This one works.
https://github.com/louisl/CodeIgniter4/blob/feature/travis-codesniffer/.travis.yml

Flags up a ton of stuff at the moment.
https://travis-ci.org/louisl/CodeIgniter4/jobs/315321638

**Comment by jim-parry** [comment]
Adding this to our travis-ci build would be handy, for sure :)

**Comment by lonnieezell** [comment]
But only after we get a chance to go through the files and clean up what we've got first :)

**Comment by louisl** [comment]
Yeah I agree, probably best have a tidy up first using it.

It will fix in bulk with the beautifier btw eg.

```./vendor/bin/phpcbf ./system --standard=./vendor/codeigniter4/codeigniter4-standard/CodeIgniter4/ruleset.xml```
