### ISSUE TITLE
Re-write the read me to reflect the new 'codeigniter4/' organisation structure

### ISSUE THREAD

**Issue by louisl** [louisl/CodeIgniter4-Standard#25]

**Comment by jim-parry** [comment]
In progress ... patience, young padawan :)

**Comment by louisl** [comment]
haha sorry, just flagging up todos, I Know I've neglected this for 11 months!

**Comment by jim-parry** [comment]
no problem ... just transferred the main repo to codeigniter4/, and have updated travis-ci.org.
packagist.org next, then I will update the links like the one you mention here.

**Comment by louisl** [comment]
Cool, I'll keep an eye out for issues.

**Comment by jim-parry** [comment]
I will probably raise an issue to revisit the sniffer rules, once things settle down a bit - probably mid-December or later. Thanks for keepig interested!

**Comment by louisl** [comment]
No problem, I expected things to change before the official release, we have a nice code base to work from. I don't really get a chance to check the forum much these days, but any issue on Github pops up in my email, also I'm available on slack most working days as '@louisl' in the Codeigniter channels so '@'ing me will get my attention. ;)
