### ISSUE TITLE
Cannot handle nested nested arrays

### ISSUE THREAD

**Issue by jim-parry** [louisl/CodeIgniter4-Standard#27]
It seems to me that phpcs/cbf are getting confused with the braced nesting of arrays in some test classes, and giving up. Two examples: I have found a single method in each of the "offending" classes that can be commented out to force a "pass"... RouterTest:testMatchedRouteOptions() and RouteColelctionTest::testRoutesOptions().
I am holding my nose at the thought of doing this, but it won't block progress. This issue remains an issue for now, and will need to be revisited.

Workaround for RouterTest is to declare the options before adding a new rule to the route collection.
It results in the following ugliness (reformatted by PHPCBF):

		$options = [
			'as'  => 'login',
			'foo' => 'baz',
		];
		$this->collection->add('foo', function () {
		}, $options);
		$options = [
			'as'  => 'admin',
			'foo' => 'bar',
		];
		$this->collection->add(
				'baz', function () {
				}, $options
		);

This is a workaround, not a solution, and smells bad :(

**Comment by louisl** [comment]
I'll take a look at this and issue #26 as soon as I get a chance.
