### ISSUE TITLE
Autoinstall standards upon composer install

### ISSUE THREAD

**Issue by KhairulA** [louisl/CodeIgniter4-Standard#28]
### Suggestion

Should autoinstall standards upon `composer install`.

Similar to [wpcs](https://github.com/WordPress/WordPress-Coding-Standards), where [Dealerdirect/phpcodesniffer-composer-installer](https://github.com/Dealerdirect/phpcodesniffer-composer-installer) can be used.

**Comment by louisl** [comment]
I’ll take a look on Monday 6th when I’m back at work. Thanks and Happy new year
